import { useState, type FormEvent } from 'react'
import { motion } from 'framer-motion'
import { ArrowUpRight, Braces, Check, ChevronRight, CircleDot, Code2, Database, Globe2, Link, Mail, Menu, Network, Server, ShieldCheck, Sparkles, Terminal, X, Zap } from 'lucide-react'

const architecture = [['Client', 'React / Next.js', Globe2], ['API gateway', 'Nginx + auth', Network], ['Services', 'Node.js / workers', Server], ['Data layer', 'Postgres + Redis', Database]] as const
const skills = [['Frontend', Code2, ['React', 'TypeScript', 'Next.js', 'Tailwind CSS']], ['Backend', Server, ['Node.js', 'Express.js', 'REST APIs', 'Authentication']], ['Data & Cloud', Database, ['PostgreSQL', 'MongoDB', 'Redis', 'Docker']], ['Tools', Terminal, ['Git', 'GitHub', 'Linux', 'Postman']]] as const
const projects = [['01', 'ARbnab', 'Full-stack web application', 'A rental marketplace built around clear domain boundaries, secure access, and an admin-first operating model.', 'Node.js · Express · MongoDB', Network], ['02', 'Commerce engine', 'Scalable commerce platform', 'A focused commerce experience with product workflows, order state, and a backend designed to grow with the catalog.', 'React · Node.js · PostgreSQL', Zap], ['03', 'Signal chat', 'Real-time communication', 'A persistent chat system that keeps presence, messages, and delivery states synchronized in real time.', 'React · Socket.IO · Redis', Network], ['04', 'IEEE cybersecurity project', 'Cybersecurity project participation', 'Participated in an IEEE cybersecurity project focused on practical security thinking, threat awareness, and collaborative problem-solving.', 'Cybersecurity · IEEE · Security research', ShieldCheck]] as const

function Reveal({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) { return <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ duration: .55, delay }}>{children}</motion.div> }
function Heading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div> }

function GraphTree() {
  return <div className="graph-tree" aria-label="System graph tree"><div className="tree-root">System</div><div className="tree-branches"><div className="tree-branch"><span>Frontend</span><i /><b>React</b><b>Next.js</b></div><div className="tree-branch"><span>Services</span><i /><b>API</b><b>Workers</b></div><div className="tree-branch"><span>Data</span><i /><b>Redis</b><b>Postgres</b></div></div></div>
}

function App() {
  const [menu, setMenu] = useState(false); const [activeNode, setActiveNode] = useState(0); const [expanded, setExpanded] = useState<number | null>(null); const [contactStatus, setContactStatus] = useState('')
  async function handleContactSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setContactStatus('Sending...')
    const form = event.currentTarget
    const payload = Object.fromEntries(new FormData(form).entries())
    try {
      const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) })
      const result = await response.json() as { message?: string }
      if (!response.ok) throw new Error(result.message ?? 'Unable to send your message.')
      form.reset()
      setContactStatus('Message sent successfully.')
    } catch (error) {
      setContactStatus(error instanceof Error ? error.message : 'Unable to send your message.')
    }
  }
  return <div className="site-shell">
    <header className="navbar"><a className="brand" href="#home"><span className="brand-mark"><Braces size={16} /></span>dev<span className="accent">/</span>portfolio</a><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X /> : <Menu />}</button><nav className={menu ? 'nav-links open' : 'nav-links'}>{['About', 'Skills', 'Projects', 'Systems', 'Experience', 'Contact'].map(item => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenu(false)}>{item}</a>)}<span className="availability"><CircleDot size={12} /> Available for opportunities</span></nav></header>
    <main>
      <div className="name-banner">RITABRATA DAS <span>Software Developer</span></div>
      <GraphTree />
      <section id="home" className="hero section-wrap"><Reveal><div className="kicker"><span className="pulse" /> Software engineer · [Your Location]</div><h1>Building software<br /><span className="outline-text">that moves</span> ideas forward.</h1><p className="hero-lede">I design and build scalable, reliable, and user-focused software systems.</p><div className="hero-actions"><a className="button primary" href="#projects">View my work <ArrowUpRight size={16} /></a><a className="button ghost" href="#contact">Let's talk <Mail size={16} /></a></div><div className="hero-meta"><span><b>05</b> selected projects</span><span><b>∞</b> curiosity in systems</span></div></Reveal><Reveal delay={.12}><div className="visual-label"><span className="pulse" /> live architecture map <span>v1.0</span></div><div className="architecture-card">{architecture.map(([label, sub, Icon], i) => <div key={label}><button className={`arch-node ${i === activeNode ? 'selected' : ''}`} onMouseEnter={() => setActiveNode(i)} onClick={() => setActiveNode(i)}><span className="node-icon"><Icon size={17} /></span><span><strong>{label}</strong><small>{sub}</small></span><ChevronRight size={15} /></button>{i < 3 && <div className="connector"><span /></div>}</div>)}<div className="arch-footer"><span><ShieldCheck size={14} /> fault tolerant by design</span><span>04 nodes</span></div></div><div className="floating-code"><span>01</span><code>const system = await<br />ship({'{ scale: true }'})</code></div></Reveal></section>
      <div className="ticker"><div>{['JavaScript', 'TypeScript', 'Node.js', 'React', 'REST APIs', 'System design', 'Docker', 'Git'].map(x => <span key={x}><Sparkles size={12} /> {x}</span>)}</div></div>
      <section id="about" className="section-wrap"><Heading eyebrow="01 / The developer" title="Craft over ceremony." /><div className="about-grid"><Reveal><p className="large-copy">I'm a software developer who enjoys turning ambiguous problems into clear, maintainable systems.</p><p className="body-copy">From backend architecture and API design to thoughtful interfaces, I care about the details that make software feel dependable. This is a placeholder profile ready for your story, experience, and point of view.</p><a className="text-link" href="#contact">More about me <ArrowUpRight size={14} /></a></Reveal><div className="stats-grid">{[['05', 'Projects shipped'], ['10+', 'Technologies used'], ['X+', 'Years learning'], ['100%', 'Engineering energy']].map(([a, b]) => <div className="stat" key={b}><strong>{a}</strong><span>{b}</span></div>)}</div></div></section>
      <section id="skills" className="section-wrap"><Heading eyebrow="02 / The toolkit" title="Tools for the real world." /><div className="skill-grid">{skills.map(([title, Icon, items], i) => <Reveal key={title} delay={i * .05}><div className="skill-card"><div className="skill-head"><span className="icon-tile"><Icon size={18} /></span><span>0{i + 1}</span></div><h3>{title}</h3>{items.map(item => <div className="skill-row" key={item}><span><Check size={11} /></span>{item}</div>)}</div></Reveal>)}</div></section>
      <section id="projects" className="section-wrap projects"><Heading eyebrow="03 / Selected work" title="Built to be useful." /><div className="project-grid">{projects.map(([num, title, type, description, tags, Icon], i) => <Reveal key={title} delay={i * .07}><article className={`project-card p${i}`}><div className="project-top"><span>{num}</span><Icon size={20} /><ArrowUpRight size={17} /></div><div className="project-art"><span><Icon size={33} /></span></div><small>{type}</small><h3>{title}</h3><p>{description}</p><div className="tags">{tags.split(' · ').map(tag => <span key={tag}>{tag}</span>)}</div><button className="expand" onClick={() => setExpanded(expanded === i ? null : i)}>{expanded === i ? 'Hide details' : 'View case study'} <ArrowUpRight size={14} /></button>{expanded === i && <div className="case-study">Auth · admin workflows · resilient APIs · clear data ownership</div>}</article></Reveal>)}</div></section>
      <section id="systems" className="section-wrap"><Heading eyebrow="04 / System design" title="How I think about systems." /><div className="system-layout"><Reveal><div className="system-diagram"><div className="diagram-meta"><span>request flow</span><span>latency_budget: 180ms</span></div><div className="flow">{['Client', 'CDN', 'Load balancer', 'API gateway', 'App servers', 'Cache', 'Database'].map((item, i) => <div className="flow-item" key={item}><div className={i === 4 ? 'flow-node active' : 'flow-node'}><small>0{i + 1}</small>{item}</div>{i < 6 && <div className="flow-line" />}</div>)}</div><div className="diagram-meta"><span>● healthy</span><span>● cached</span><span>● persistent</span></div></div></Reveal><Reveal delay={.1}><div className="system-notes"><span className="eyebrow">The principles</span><h3>Good architecture makes the right thing easier.</h3><p>I think in boundaries, feedback loops, and failure modes. The goal is not complexity; it's a system that stays understandable as it grows.</p>{['Scalability', 'Caching', 'API design', 'Fault tolerance', 'Security', 'Observability'].map((x, i) => <div className="topic" key={x}><span>0{i + 1}</span>{x}<ArrowUpRight size={13} /></div>)}</div></Reveal></div></section>
      <section id="experience" className="section-wrap experience"><Heading eyebrow="05 / Experience & education" title="Still learning. Always building." /><div className="timeline"><div className="timeline-item"><i /><span>2023 — 2027</span><h3>B.Tech</h3><b>Techno India University</b><p>Building a foundation across Data Structures & Algorithms, Database Management Systems, Operating Systems, Computer Networks, Object-Oriented Programming, and Software Engineering.</p></div><div className="timeline-item"><i /><span>2022</span><h3>Higher Secondary</h3><b>Narit Nayaratna Institution</b><p>Completed higher-secondary education while developing an early interest in technology and problem-solving.</p></div><div className="timeline-item"><i /><span>2010</span><h3>Secondary</h3><b>Nowpara High School</b><p>Completed secondary education and began the academic journey that led toward software engineering.</p></div></div></section>
      <section className="philosophy"><div className="section-wrap philosophy-inner"><span className="eyebrow">06 / Developer philosophy</span><h2>Build. Learn.<br /><em>Improve. Repeat.</em></h2><div className="principles">{['Write clean code', 'Design for scale', 'Keep systems simple', 'Learn continuously', 'Solve real problems'].map((x, i) => <div key={x}><span>0{i + 1}</span>{x}</div>)}</div></div></section>
      <section id="contact" className="section-wrap contact"><div><span className="eyebrow">07 / Contact</span><h2>Let's build<br /><em>something great.</em></h2><p>Have a problem worth solving? I'd like to hear about it.</p><div className="contact-links"><a href="mailto:ritabratadasown@gmail.com"><Mail size={16} /> ritabratadasown@gmail.com</a><a href="https://github.com/Ritabrata90" target="_blank" rel="noreferrer"><Link size={16} /> github.com/Ritabrata90</a><a href="https://www.linkedin.com/in/ritabrata-das-23480b2a6" target="_blank" rel="noreferrer"><Link size={16} /> linkedin.com/in/ritabrata-das</a></div></div><form className="contact-form" onSubmit={handleContactSubmit}><label>Name<input name="name" placeholder="Your name" required /></label><label>Email<input name="email" type="email" placeholder="you@company.com" required /></label><label>Subject<input name="subject" placeholder="What are we building?" required /></label><label>Message<textarea name="message" placeholder="Tell me a little about the project..." rows={4} required /></label><button className="button primary" type="submit">Send message <ArrowUpRight size={16} /></button>{contactStatus && <p role="status">{contactStatus}</p>}</form></section>
    </main><footer><span className="brand"><span className="brand-mark"><Braces size={16} /></span>dev<span className="accent">/</span>portfolio</span><span>Building software that solves real problems.</span><span>© 2026 [Your Name]</span></footer><a className="back-top" href="#home" aria-label="Back to top"><ArrowUpRight size={16} /></a>
  </div>
}
export default App
